config/routes.rb
Rails.application.routes.draw do

# we pass resources :posts to the resources :topics block. This nests the post routes under the topic routes.
  resources :topics do
    # creates all routes for :posts except for the index route
    resources :posts, except: [:index]
  end

  # we use only: [] because we don't want to create any  /posts/:id routes, just posts/:post_id/comments routes
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]


  resources :sessions, only: [:new, :create, :destroy]


  # Allows users to visit /about rather than /welcome/about
  get 'about' => 'welcome#about'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent:(:destroy)
  has_many :favorites, dependent:(:destroy)

  has_many :votes, dependent:(:destroy)

  default_scope { order('rank DESC') }

  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  scope :order_by_title, -> { order('title ASC') }

  # # the above could also be written
  # def self.ordered_by_title
  #   order('title DESC')
  # end


  scope :order_by_reverse_created_at, -> { order('created_at ASC') }

  # the above could also be written
  # def self.ordered_by_reverse_created_at
  #   order('created_at ASC')
  # end


  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  # count the number of up_votes (votes implies self.votes)
  def up_votes
    votes.where(value: 1).count
  end
  # count the number of down_votes
  def down_votes
    votes.where(value: -1).count
  end
  # sum the values (1 or -1) of every vote
  def points
    votes.sum(:value)
  end

  def total_votes
    votes.count
  end

  def total_comments
    comments.count
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # the before_action filter calls require_sign_in before each
  # controller action except for :show
  before_action :require_sign_in, except: :show

  before_action :authorize_user, except: [:show, :new, :create]

  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def create
    # @post = Post.new
    # @post.title = params[:post][:title]
    # @post.body = params[:post][:body]
    @topic = Topic.find(params[:topic_id])
    # @post.topic = @topic
    # above @post parameters mass assigned below
    # post_params is a private method def at bottom
    @post = @topic.posts.build(post_params)
    @post.user = current_user

    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    # @post.title = params[:post][:title]
    # @post.body = params[:post][:body]
    @post.assign_attributes(post_params)

    if @post.save
      flash[:notice] = "Post was updated."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render(:edit)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    # we call destroy on @post, if that call is successufl, we set a flash message and redirect the user to the posts index view. if destroy fails then we redirect the user to the show view using render :show
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to(@post.topic)
    else
      flash.now[:alert] = "There was an error deleting the post."
      render(:show)
    end
  end

  # private methods go below this line
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_user
    post = Post.find(params[:id])
    # We redirect the user unless they own the post they're attempting to modify, or they're an admin
    unless current_user == post.user || current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to [post.topic, post]
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin? || current_user.moderator?)
  end
end

app/views/posts/_form.html.erb
<!-- The underscore at the beginning of a file name lets Rails know that it's a parWe use the topic and post local variables we passed into the partial when we rendered it-->
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label(:title) %>
    <%= f.text_field(:title, class: 'form-control', placeholder: "Enter post title") %>
  <% end %>
  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label(:body) %>
    <%= f.text_area(:body, rows: 8, class: 'form-control', placeholder: "Enter post body") %>
  <% end %>
  <div class="form-group">
    <%= f.submit("Save", class: 'btn btn-success') %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
  <%= render partial: 'votes/voting', locals: { post: post } %>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to post.title, topic_post_path(post.topic, post) %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
      <%= post.comments.count %> Comments
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it ryhmes.</li>
      <li>Don't use the letter "A"</li>
      <li>The incessant use of hashtags will get you banned</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Posts</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it ryhmes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>
</div>

app/views/posts/show.html.erb
<div>
  <%= render partial: 'votes/voting', locals: { post: @post } %>
  <h1>
    <%= @post.title %> <br>
    <small>
      submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
    </small>
  </h1>
</div>

<div class="row">
  <div class="col-md-8">
    <p><%= @post.body %></p>
  </div>
    <% if user_is_authorized_for_post?(@post) %>
      <div class="col-md-4">
      <!-- we format a link as an Edit button which directs a user to /posts/@post.id/edit  -->
      <%= link_to("Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success') %>
      <%= link_to("Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'}) %>
      </div>
    <% end %>
    <div class="col-md-4">
      <h3>
        <%= pluralize(@post.points, 'point') %>
        <div>
          <small>
            <%= pluralize(@post.up_votes, 'up-vote') %>,
            <%= pluralize(@post.down_votes, 'down-vote') %>
          </small>
        </div>
      </h3>
      <% if current_user %>
        <%= render partial: 'favorites/favorite', locals: { post: @post } %>
      <% end %>
    </div>
  <div class="col-md-8">
    <h3>Comments</h3>
    <%= render @post.comments %>
  </div>
  <div class="col-md-8">
    <% if current_user %>
      <%= render 'comments/form', comment: Comment.new, post: @post %>
    <% end %>
  </div>
</div>
<!-- Above Comments render could also be written
<% @post.comments.each do |comment| %>
  <%= render({ partial: 'comments/comment', locals: {comment: comment} }) %>
<% end %> -->